version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
    environment:
     - DATABASE_URL=mongodb://mongo-compose/todos 
  mongo-compose:
    image: mongo:6.0.1
    ports:
      - 27017:27017
    volumes:
      - mongodb-compose:/data/db
volumes:
 mongodb-compose:
